[2021-11-10 15:50:44,592] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop manual__2021-11-10T14:50:25.031474+00:00 [queued]>
[2021-11-10 15:50:44,603] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop manual__2021-11-10T14:50:25.031474+00:00 [queued]>
[2021-11-10 15:50:44,603] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-10 15:50:44,603] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-11-10 15:50:44,604] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-10 15:50:44,609] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): run_after_loop> on 2021-11-10 14:50:25.031474+00:00
[2021-11-10 15:50:44,610] {standard_task_runner.py:52} INFO - Started process 250182 to run task
[2021-11-10 15:50:44,611] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'example_bash_operator', 'run_after_loop', 'manual__2021-11-10T14:50:25.031474+00:00', '--job-id', '22', '--raw', '--subdir', '/home/dnieto/.pyenv/versions/3.8.11/envs/***/lib/python3.8/site-packages/***/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpqslutypl', '--error-file', '/tmp/tmp6xluonjp']
[2021-11-10 15:50:44,612] {standard_task_runner.py:77} INFO - Job 22: Subtask run_after_loop
[2021-11-10 15:50:44,635] {logging_mixin.py:109} INFO - Running <TaskInstance: example_bash_operator.run_after_loop manual__2021-11-10T14:50:25.031474+00:00 [running]> on host workstation
[2021-11-10 15:50:44,664] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=run_after_loop
AIRFLOW_CTX_EXECUTION_DATE=2021-11-10T14:50:25.031474+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-11-10T14:50:25.031474+00:00
[2021-11-10 15:50:44,664] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-11-10 15:50:44,664] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo 1']
[2021-11-10 15:50:44,667] {subprocess.py:85} INFO - Output:
[2021-11-10 15:50:44,668] {subprocess.py:89} INFO - 1
[2021-11-10 15:50:44,668] {subprocess.py:93} INFO - Command exited with return code 0
[2021-11-10 15:50:44,682] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=run_after_loop, execution_date=20211110T145025, start_date=20211110T145044, end_date=20211110T145044
[2021-11-10 15:50:44,703] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-10 15:50:44,719] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
